# Generated by Django 4.0.2 on 2022-04-03 07:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='due',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
